apps/base/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import views as views_auth

from .views import RegistroUsuario

app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', views_auth.logout_then_login, {'login_url': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('registro/', RegistroUsuario.as_view(), name="registro"),  
]

apps/listas/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListaCreate, ListaDelete, ListaUpdate, listas_list, agregarProducto, ListaDetail, quitarProducto

app_name='listas'

urlpatterns = [
    path('',listas_list,name="lista_list"),
    path('crear/',ListaCreate.as_view(),name="lista_form"),
    path('ver/<int:pk>',ListaDetail.as_view(),name="lista_detail"),
    path('editar/<int:pk>',ListaUpdate.as_view(),name="lista_update"),
    path('borrarProducto/<int:pk>',ListaDelete.as_view(),name="lista_delete"),
    path('agregar-producto',agregarProducto,name="lista_add_producto"),
    path('quitar-producto',quitarProducto,name="lista_remove_producto"),   
]

apps/productos/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductoList, ProductoCreate, ProductoDelete, ProductoUpdate, productos_list

app_name='productos'

urlpatterns = [
    
    path('listarProducto/',productos_list, name="producto_list"),
    path('crearProducto/', ProductoCreate.as_view(), name="producto_form"),
    path('editarProducto/<int:pk>', ProductoUpdate.as_view(), name="producto_update"),
    path('borrarProducto/<int:pk>', ProductoDelete.as_view(), name="producto_delete")
]

apps/tiendas/urls.py
from django.urls import path
from .views import TiendasList, TiendasCreate, TiendasUpdate, TiendasDelete, tiendas_list

app_name = 'tiendas'

urlpatterns = [
    path('', tiendas_list, name="tiendas_list"),
    path('crear/', TiendasCreate.as_view(), name="tiendas_form"),
    path('editar/<int:pk>', TiendasUpdate.as_view(), name="tiendas_update"),
    path('borrar/<int:pk>', TiendasDelete.as_view(), name="tiendas_delete"),
]

examen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    # path('', include('pwa.urls')),
    path('', include('social.apps.django_app.urls', namespace='social')), #social
    path('', include('apps.base.urls'), name="base"),
    path('admin/', admin.site.urls, name="admin"),
    path('tiendas/', include('apps.tiendas.urls'), name="tiendas"),
    path('productos/', include('apps.productos.urls'), name="productos"),
    path('login', include('apps.base.urls'), name="login"),
    path('logout', include('apps.base.urls'), name="logout"),
    path('listas/', include('apps.listas.urls'), name="listas"),
    
]

apps/base/models.py
from django.db import models
# from apps.tiendas.models import Tienda

# Create your models here.




    

apps/base/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

class RegistroForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = {
            'username',
            'email',
            'password1',
            'password2',
            }
        order_fields={
            'username',
            'email',
            'password1',
            'password2',
            }
        labels = {
            'username':'Nombre de Usuario',
            'email':'Email',
            'password1':'Contraseña',
            'password2':'Repita Contraseña',
            }
        widgets = {
            'username' : forms.TextInput(attrs={'type': 'text','class':'form-control','required':''}),
            'email' : forms.TextInput(attrs={'type': 'email','class':'form-control','required':''}),
            'password1' : forms.TextInput(attrs={'type': 'password','class':'form-control','required':''}),
            'password2' : forms.TextInput(attrs={'type': 'password','class':'form-control','required':''}),
            }
        error_messages = {
            'required':'<font color="red">Campo Obligatorio',
        }

    def save(self, commit=True):
        user = super(RegistroForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.password1 =self.cleaned_data["password1"]
        user.password2 =self.cleaned_data["password2"]
        if commit:
            user.save()
        return user

apps/base/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm
# Create your views here.

def home(request):
    return render(request, 'home.html')

class RegistroUsuario(CreateView):
    model = get_user_model()
    template_name = "registro.html"
    form_class = RegistroForm
    success_url = reverse_lazy('base:home')

apps/base/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
{% load pwa %}
<head>
    {% progressive_web_app_meta %}

    <!-- Titulo -->
    <title>Lista - {% block title %} Title {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <uses-permission android:name="android.permission.INTERNET"/>
    
    <!-- Estilos -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    {% block head %}
    {% endblock %}

</head>
<body>
    <script src="{% static 'js/push.min.js'%}"></script>
    <header>      
    {% block navbar %}
    <!-- Cabezera -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary py-2">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo1.png' %}" width="30" height="30" alt="Inicio">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'base:home' %}">Inicio <span class="sr-only">(current)</span></a>
        </li>

        {% if not user.is_authenticated %}        
        
        <li class="nav-item">
            <a class="nav-link" href="{% url 'base:login' %}">Iniciar sesión</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'base:registro' %}">Registrarse</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link lista-nav" href="{% url 'listas:lista_list' %}">Listas</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:producto_list' %}">Productos</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'tiendas:tiendas_list' %}">Tiendas</a>
        </li>

        </ul>        
        <ul class="navbar-nav flex-row ml-lg-auto d-none d-lg-flex">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><strong style="color: white;">Usuario:</strong> {{ user.get_username }}</a>
                <div class="dropdown-menu" x-placement="bottom-start" >
                <a class="dropdown-item" href="{% url 'base:logout' %}">Cerrar Sesión</a>
            </li>
        </ul>
        {% endif %}
    </div>
    </nav>
    </header>
    {% endblock %}

    {% block header %}   
    {% endblock %}

    <div class="content">
        <div class="col-md-12 mt-3 mb-5">
            {% block content %}
            {% endblock %}
        </div>
    </div>


{% block footer %}
{% if user.is_authenticated %}
<ul class="navbar-nav navbar-dark bg-info d-lg-none">
    <ul class="navbar-nav m-3">
        <li class="nav-item">
            <strong>Usuario:</strong> {{ user.get_username }}
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'base:logout' %}">Cerrar sesión</a></li>
    </ul>
</ul>
{% endif %}
<!-- Pie de página -->
<footer class="footer bg-dark p-2 pb-2">
<div class="row">
    <div class="col-12 ml-2 mr-2">
        <ul class="list-unstyled">            
            <li>Desarrollo de Aplicaciones Web y Mobile | 2018</li>
            <li>Ariel Chacon, Nicolás Leporati, Nicolás Meli, Nicolás Pino</li>
            <li>Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/master/LICENSE">MIT License</a>.</li>
            <li>Based on <a href="https://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="http://fontawesome.io/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="https://fonts.google.com/" rel="nofollow">Google</a>.</li>
            <br> <li><a href="/admin">Ingresar a Administración</a></li> 
        </ul>
    </div>
</div>

</footer>
{% endblock %}
    
   

<!-- Scripts -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/lista-productos.js' %}"></script>
{% block extrajs %}
{% endblock %}

</body>
</html>

apps/base/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
{% if user.is_authenticated %}
<div id="home">
<div class="col-8 p-0 pt-2">
  <h1>Bienvenido {{ user.get_full_name }}!</h1>
  <p>Recuerda agregar tus tiendas y productos antes de comenzar a crear tus listas!</p>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <!-- <h1>Bienvenido {{ user.username }}!</h1> -->
</div>

{% else %}
<img src="{% static 'images/home.png' %}" id="home-image" class="d-none d-xl-block position-absolute" style="left:1em; top:-4em;">

<div class="d-none d-xl-block col-md-4 col-center text-center mb-5 mt-5 jumbotron" id="home" style="top: 7em; left:20em;">  
  <h1 class="display-4">Comienza a Organizar tus Compras!</h1>
  <a href="{% url 'base:login' %}" class="btn btn-primary mt-3 mb-2">Iniciar sesión</a>
  <p class="mb-1">o</p>
  <a href="{% url 'base:registro' %}">Registrarse</a>  
</div>
<div class="d-sm-block d-xl-none col-center text-center" id="home" >
    <div class="col-lg-4 mx-auto">
    <h1 class="display-4">Comienza a Organizar tus Compras!</h1>
    <a href="{% url 'base:login' %}" class="btn btn-primary mt-3 mb-2">Iniciar sesión</a>
    <p class="mb-1">o</p>
    <a href="{% url 'base:registro' %}">Registrarse</a>
  </div>
  </div>
<br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endif %}
{% endblock %}

apps/base/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div id="registro" class="col-lg-4 mx-auto mb-5 mt-5">
    
    <h1 class="display-4">Login</h1><br>

    <form method="POST" id="formulario">
        {% csrf_token %}

        <div class="form-group">
            <label for="username">Nombre de Usuario</label><br>
            <input name="username" class="form-control" type="text"/>
            <div class="bg-danger mt-1">{{ form.errors.username }}</div>
        </div>

        <div class="form-group">
            <label for="password">Password</label><br>
            <input name="password" class="form-control" type="password"/>
            <div class="bg-danger mt-1">{{ form.errors.password }}</div>
        </div>

        {% if form.non_field_errors %}
        <div class="form-group">
            <div class="bg-danger mt-1 p-2">Login incorrecto!</div>
        </div>  
        {% endif %}
        
        <!-- {{form.non_field_errors}} -->                

        <div class="form-row align-items-center">

            <div class="col-auto mr-auto">
                <input class="btn btn-success" type="submit" value="Login"/>
            </div>

            <div class="col-auto form-inline">
                <span style="font-size: 32px; color: Dodgerblue;">
                    <i class="fab fa-facebook"></i>
                </span>
                <a href="{% url 'social:begin' 'facebook' %}" class="ml-2 mr-3">Facebook Login</a>

                <span style="font-size: 32px; color: firebrick;">
                    <i class="fab fa-google"></i>
                </span>
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="ml-2">Google Login</a>
            </div>
        </div>
        
    </form>
    <br><br><br>
</div>
{% endblock %}

apps/base/templates/registro.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
{% if user.is_authenticated %}
<div id="home">
<div class="col-8 p-0 pt-2">
  <h1>Bienvenido {{ user.get_full_name }}! Ya estas registrado!</h1>
  <br><br><br><br><br><br><br>
</div>

{% else %}
<div id="registro" class="col-lg-4 mx-auto mb-5 mt-5">
    
    <h1 class="display-4">Registro</h1><br>

    <form method="POST" id="formulario">
        {% csrf_token %}

        <div class="form-group">
            <label for="username">Nombre de Usuario</label><br>
            <input name="username" class="form-control" type="text"/>
            <div class="bg-danger mt-1">{{ form.errors.username }}</div>
        </div>

        <div class="form-group">
            <label for="email">Email</label><br>
            <input name="email" class="form-control" type="text"/>
            <div class="bg-danger mt-1">{{ form.errors.username }}</div>
        </div>

        <div class="form-group">
            <label for="password1">Contraseña</label><br>
            <input name="password1" class="form-control" type="password"/>
            <div class="bg-danger mt-1">{{ form.errors.password1 }}</div>
        </div>

        <div class="form-group">
            <label for="password2">Repetir Contraseña</label><br>
            <input name="password2" class="form-control" type="password"/>
            <div class="bg-danger mt-1">{{ form.errors.password2 }}</div>
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Registrarse"/>
        </div>

{% endif %}
{% endblock %}