apps/productos/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductoList, ProductoCreate, ProductoDelete, ProductoUpdate, productos_list

app_name='productos'

urlpatterns = [
    
    path('listarProducto/',productos_list, name="producto_list"),
    path('crearProducto/', ProductoCreate.as_view(), name="producto_form"),
    path('editarProducto/<int:pk>', ProductoUpdate.as_view(), name="producto_update"),
    path('borrarProducto/<int:pk>', ProductoDelete.as_view(), name="producto_delete")
]

apps/tiendas/urls.py
from django.urls import path
from .views import TiendasList, TiendasCreate, TiendasUpdate, TiendasDelete, tiendas_list

app_name = 'tiendas'

urlpatterns = [
    path('', tiendas_list, name="tiendas_list"),
    path('crear/', TiendasCreate.as_view(), name="tiendas_form"),
    path('editar/<int:pk>', TiendasUpdate.as_view(), name="tiendas_update"),
    path('borrar/<int:pk>', TiendasDelete.as_view(), name="tiendas_delete"),
]

examen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    # path('', include('pwa.urls')),
    path('', include('social.apps.django_app.urls', namespace='social')), #social
    path('', include('apps.base.urls'), name="base"),
    path('admin/', admin.site.urls, name="admin"),
    path('tiendas/', include('apps.tiendas.urls'), name="tiendas"),
    path('productos/', include('apps.productos.urls'), name="productos"),
    path('login', include('apps.base.urls'), name="login"),
    path('logout', include('apps.base.urls'), name="logout"),
    path('listas/', include('apps.listas.urls'), name="listas"),
    
]

apps/productos/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
import json
# Create your models here.

PRODUCTO_ESTADOS = (

   ('Listo', 'Listo'),
   ('Pendiente', 'Pendiente'),

)

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    costoPresupuestado = models.IntegerField()
    costoReal = models.IntegerField(default=0)
    tienda = models.ForeignKey('tiendas.Tienda', on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=PRODUCTO_ESTADOS, default='Pendiente')
    notas = models.CharField(max_length=50, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre 

    @property
    def json(self):
        return json.dumps(self)  

class ProductosForm(forms.ModelForm):

    class Meta:
        model=Producto
        fields = [
            'nombre',
            'costoPresupuestado',
            'costoReal',
            'estado',
            'notas',
            'tienda'
        ]
        labels = {
            'nombre':'Nombre',
            'costoPresupuestado':'Costo Presupuestado',
            'costoReal':'Costo Real',
            'estado':'Estado',
            'notas':'Notas',
            'tienda':'Tienda'
        }
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'forms-control'}),
            'costoPresupuestado':forms.TextInput(attrs={'class':'forms-control'}),
            'costoReal':forms.TextInput(attrs={'class':'forms-control'}),
            'estado':forms.Select(choices="PRODUCTO_ESTADOS",attrs={'class':'forms-control'}),
            'notas':forms.TextInput(attrs={'class':'forms-control'}),
            'tienda':forms.Select(attrs={'class':'forms-control'}),
        }

apps/productos/forms.py
from .models import Producto
from apps.tiendas.models import Tienda
from django import forms

class ProductosForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tienda'].queryset = (Tienda.objects.filter(estado="APROBADA") | Tienda.objects.filter(autor=request.user)).distinct()
    
    class Meta:
        model=Producto
        fields = [
            'nombre',
            'costoPresupuestado',
            'costoReal',
            'estado',
            'notas',
            'tienda'
        ]
        labels = {
            'nombre':'Nombre',
            'costoPresupuestado':'Costo Presupuestado',
            'costoReal':'Costo Real',
            'estado':'Estado',
            'notas':'Notas',
            'tienda':'Tienda'
        }
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'costoPresupuestado':forms.TextInput(attrs={'class':'form-control'}),
            'costoReal':forms.TextInput(attrs={'class':'form-control'}),
            'estado':forms.Select(choices="PRODUCTO_ESTADOS",attrs={'class':'form-control'}),
            'notas':forms.TextInput(attrs={'class':'form-control'}),
            'tienda':forms.Select(attrs={'class':'form-control'})
        }

apps/productos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core import serializers
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Producto
from .forms import ProductosForm
from apps.listas.models import Lista

from django.contrib.auth.mixins import LoginRequiredMixin

class OwnershipMixin(object):
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        current_user = self.request.user
        object_owner = getattr(self.get_object(), 'usuario')

        if current_user != object_owner:
            return redirect('productos:productos_list')
        return super(OwnershipMixin, self).dispatch(request, *args, **kwargs)

# Create your views here.

class ProductoList (LoginRequiredMixin,ListView):
    login_url = '/login/'
    model = Producto
    template_name = 'productos/producto_list.html'

@login_required(login_url='/')
def productos_list(request):
    productos = Producto.objects.filter(usuario=request.user)
    context = {'productos':productos}
    
    return render(request, 'productos/producto_list.html', context)

class ProductoCreate (LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Producto
    
    form_class = ProductosForm
    template_name = 'productos/producto_form.html'

    def get_success_url(self):
        next = self.request.GET.get('next', '')
        id = self.request.GET.get('id', '0')
        if next == 'listas':
            if id != '0':
                self.success_url = reverse_lazy('listas:lista_detail', args=[id])
            else:
                self.success_url = reverse_lazy('listas:lista_list')
        else:
            self.success_url = reverse_lazy('productos:producto_list')    
        return self.success_url

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(ProductoCreate, self).form_valid(form)

    def get_form_kwargs(self):
       kwargs = super().get_form_kwargs()
       kwargs.update({'request': self.request})
       return kwargs

class ProductoUpdate (OwnershipMixin, UpdateView):

    login_url = '/login/'
    model = Producto    
    form_class = ProductosForm
    template_name = 'productos/producto_form.html'

    def get_success_url(self):
        next = self.request.GET.get('next', '')
        id = self.request.GET.get('id', '0')
        if next == 'listas':
            if id != '0':
                self.success_url = reverse_lazy('listas:lista_detail', args=[id])
            else:
                self.success_url = reverse_lazy('listas:lista_list')
        else:
            self.success_url = reverse_lazy('productos:producto_list')    
        return self.success_url

    def get_form_kwargs(self):
       kwargs = super().get_form_kwargs()
       kwargs.update({'request': self.request})
       return kwargs

    def form_valid(self, form):
        producto = Producto.objects.get(id=self.object.id)
        listas = producto.lista_set.all()
        for lista in listas:
            lista.costoTotalReal = lista.costoTotalReal - producto.costoReal        
        for lista in listas:
            lista.costoTotalReal = lista.costoTotalReal + self.object.costoReal
            lista.save()
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

class ProductoDelete (OwnershipMixin,DeleteView):

    login_url = '/login/'
    model = Producto
    template_name = 'productos/producto_delete.html'
    success_url = reverse_lazy('productos:producto_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        listas = self.object.lista_set.all()
        for lista in listas:
            lista.costoTotalReal = lista.costoTotalReal - self.object.costoReal        
            lista.save()
        print(listas)
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

apps/productos/templates/productos/producto_delete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-md-12 p-0">

    <h3 class="display-3">Productos</h3>
    <hr>

    <form method="POST">{% csrf_token %}

        <div>       
            <h3>¿Desea eliminar el producto {{ object.nombre }}?</h3>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-secondary" href="{% url 'productos:producto_list' %}">Cancelar</a>
            <br>
        </div>

    </form>
    <br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

apps/productos/templates/productos/producto_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Ingreso de Productos{% endblock %}

{% block content %}
<h1>Productos</h1>
<div class="col-lg-4 p-0">
<form method="post">    
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.name}}">{{ field.label_tag }}</label><br>            
        {{ field }}
        <div class="bg-danger mt-1">{{ field.errors }}</div>
    </div>
    {% endfor %}
    
    <div class="bg-danger mt-1 mb-2">{{ form.non_field_errors }}</div>

    <input type="submit" class="btn btn-success" value="Guardar" />
    <a class="ml-2" href="{% url 'productos:producto_list' %}">cancelar</a>
    <p class="text-muted">* Se debe esperar a que un administrador acepte la tienda, hasta entonces solo se podra usar la nueva tienda de manera personal.</p>
    {% if object %}
        <p>¿Tu tienda no esta en la lista? <a href="{% url 'tiendas:tiendas_form' %}?next=productos&id={{object.id}}">Agregar tienda</a></p>
    {% else %}
        <p>¿Tu tienda no esta en la lista? <a href="{% url 'tiendas:tiendas_form' %}?next=productos">Agregar tienda</a></p>
    {% endif %}
</form>
{{next}}
</div>
{% endblock %}

apps/productos/templates/productos/producto_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<h3 class="display-3">Productos</h3>
<hr>
<a class="btn btn-secondary" role="button" href="{% url 'productos:producto_form' %}">Agregar</a>
<hr>

<div class="col-md-8 p-0">
{% if not productos %}

<p class="bg-danger p-2">No ha ingresado productos a la lista</p>
<br><br><br><br><br><br><br>

{% else %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-light bg-primary">

            <tr>
                <td>Nombre</td>
                <td>Costo Presupuestado</td>
                <td>Costo Real</td>
                <td>Tienda</td>
                <td>Estado</td>
                <td>Notas</td>
                <td>Acciones</td>            
            </tr>

        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td>{{ producto.nombre }}</td>
                <td>${{ producto.costoPresupuestado }}</td>
                <td>${{ producto.costoReal | default_if_none:"0" }}</td>
                <td>{{ producto.tienda }}</td>
                <td>{{ producto.estado }}</td>
                <td>{{ producto.notas | default_if_none:"" }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{% url 'productos:producto_update' producto.id %}" title="Editar"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-sm btn-danger" href="{% url 'productos:producto_delete' producto.id %}" title="Eliminar"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endif %}

</div>

{% endblock %}