apps/listas/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListaCreate, ListaDelete, ListaUpdate, listas_list, agregarProducto, ListaDetail, quitarProducto

app_name='listas'

urlpatterns = [
    path('',listas_list,name="lista_list"),
    path('crear/',ListaCreate.as_view(),name="lista_form"),
    path('ver/<int:pk>',ListaDetail.as_view(),name="lista_detail"),
    path('editar/<int:pk>',ListaUpdate.as_view(),name="lista_update"),
    path('borrarProducto/<int:pk>',ListaDelete.as_view(),name="lista_delete"),
    path('agregar-producto',agregarProducto,name="lista_add_producto"),
    path('quitar-producto',quitarProducto,name="lista_remove_producto"),   
]

apps/productos/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductoList, ProductoCreate, ProductoDelete, ProductoUpdate, productos_list

app_name='productos'

urlpatterns = [
    
    path('listarProducto/',productos_list, name="producto_list"),
    path('crearProducto/', ProductoCreate.as_view(), name="producto_form"),
    path('editarProducto/<int:pk>', ProductoUpdate.as_view(), name="producto_update"),
    path('borrarProducto/<int:pk>', ProductoDelete.as_view(), name="producto_delete")
]

examen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    # path('', include('pwa.urls')),
    path('', include('social.apps.django_app.urls', namespace='social')), #social
    path('', include('apps.base.urls'), name="base"),
    path('admin/', admin.site.urls, name="admin"),
    path('tiendas/', include('apps.tiendas.urls'), name="tiendas"),
    path('productos/', include('apps.productos.urls'), name="productos"),
    path('login', include('apps.base.urls'), name="login"),
    path('logout', include('apps.base.urls'), name="logout"),
    path('listas/', include('apps.listas.urls'), name="listas"),
    
]

apps/listas/models.py
from django.db import models
from django import forms
from django.contrib.auth import get_user_model
import json

# Create your models here.

LISTA_ESTADOS = (
    ('Pendiente','pendiente'),
    ('Terminada','terminada'),
)


class Lista(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    costoTotalReal = models.IntegerField(default=0)
    costoTotalPresupuestado = models.IntegerField()
    estado = models.CharField(max_length=20, choices=LISTA_ESTADOS, default='Pendiente')
    productos = models.ManyToManyField('productos.Producto')
    usuario = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

    @property
    def json(self):
        return json.dumps(self)

    def __str__(self):
        return self.nombre
    
    

apps/listas/forms.py
from .models import Lista
from django import forms


class ListaForm(forms.ModelForm):

    class Meta:
        model=Lista
        fields = [
            'nombre',
            'costoTotalPresupuestado',
            # 'costoTotalReal',           
            'estado',          
        ]
        labels = {
            'nombre':'Nombre',
            # 'costoTotalReal':'Costo Total Real',
            'costoTotalPresupuestado':'Costo Total Presupuestado',
            'estado':'Estado',            
        }
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            # 'costoTotalReal':forms.TextInput(attrs={'class':'form-control'}),
            'costoTotalPresupuestado':forms.TextInput(attrs={'class':'form-control'}),
            'estado':forms.Select(choices="LISTA_ESTADOS",attrs={'class':'form-control'}),
            # 'productos':forms.SelectMultiple(attrs={'class':'form-control'}),
        }

apps/listas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Lista
from apps.productos.models import Producto
from .forms import ListaForm

class OwnershipMixin(object):
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        current_user = self.request.user
        object_owner = getattr(self.get_object(), 'usuario')

        if current_user != object_owner:
            return redirect('listas:lista_list')
        return super(OwnershipMixin, self).dispatch(request, *args, **kwargs)

# Create your views here.

@login_required(login_url='/')
def listas_list(request):
    listas = Lista.objects.filter(usuario=request.user)
    json = serializers.serialize('json', listas)    
    context = {'listas':listas, 'json':json}
    
    return render(request, 'listas/lista_list.html', context)

@login_required(login_url='/')
def agregarProducto(request):    
    if request.method == 'GET':
        lista = Lista.objects.get(id=request.GET['lista'])
        producto = Producto.objects.get(id=request.GET['producto'])

        lista.costoTotalReal = lista.costoTotalReal + producto.costoReal
        print(lista.costoTotalReal)

        lista.productos.add(producto)
        lista.save()
        return redirect('listas:lista_detail', pk=lista.id)


    return render(request, 'listas/lista_list.html')

@login_required(login_url='/')
def quitarProducto(request):    
    if request.method == 'GET':
        lista = Lista.objects.get(id=request.GET['lista'])
        producto = Producto.objects.get(id=request.GET['producto'])

        lista.costoTotalReal = lista.costoTotalReal - producto.costoReal

        lista.productos.remove(producto)                
        lista.save()
        return redirect('listas:lista_detail', pk=lista.id)


    return render(request, 'listas/lista_list.html')

class ListaDetail(OwnershipMixin, DetailView):
    model = Lista
    context_object_name = 'lista'
    template_name = 'listas/lista_detail.html'

    # success_url = reverse_lazy('listas:lista_list')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['productos'] = Lista.objects.get(id=self.object.id).productos.all()
        context['productos'] = self.object.productos.all()
        context['productosJson'] = serializers.serialize('json', self.object.productos.all()) 
        context['listaProductos'] = Producto.objects.filter(usuario=self.request.user)
        return context

class ListaCreate (LoginRequiredMixin,CreateView):
    login_url = '/login/'
    model = Lista
    form_class = ListaForm
    template_name = 'listas/lista_form.html'
    success_url = reverse_lazy('listas:lista_list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        obj.save()
        return super().form_valid(form)

class ListaUpdate (UpdateView):
    model = Lista
    form_class = ListaForm
    template_name = 'listas/lista_form.html'
    success_url = reverse_lazy('listas:lista_list')


class ListaDelete (LoginRequiredMixin,DeleteView):
    login_url = '/login/'
    model = Lista
    template_name = 'listas/lista_delete.html'
    success_url = reverse_lazy('listas:lista_list')

apps/listas/templates/listas/lista_delete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-md-12 p-0">

    <h3 class="display-3">Listas</h3>
    <hr>

    <form method="POST">{% csrf_token %}

        <div>       
                <h3>¿Desea eliminar la lista {{ object.nombre }}?</h3>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-secondary" href="{% url 'listas:lista_list' %}">Cancelar</a>
            <br>
        </div>

    </form>
    <br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

apps/listas/templates/listas/lista_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Lista {% endblock %}

{% block content %}
<div class="">    

<form method="post" class="row p-2">
    {% csrf_token %}
    
    <!-- Cabezera -->
    <div class="col-md-12 p-0 pb-3">
        <h3 class="display-3 d-inline-block">Lista: {{lista.nombre}}</h3>
        <span class="ml-3">{{lista.estado}}</span>
        <hr>
        <h4>Costo Total Presupuestado: ${{lista.costoTotalPresupuestado }}</h4>
        <h1>Costo Total Real: ${{lista.costoTotalReal}}</h1>
    </div>

    <!-- Productos en la lista -->
    <p>¿Tu producto no esta en la lista? <a href="{% url 'productos:producto_form' %}?next=listas&id={{lista.id}}">Agregar producto</a></p>
    <div class="col-lg-9 p-0 pr-2">
        {% if not productos %}
        <p class="bg-danger p-2">No has ingresado productos a la lista.</p>

        {% else %}
        <div class="table-responsive">
            <table class="table table-hover">
                <thead class="thead-light bg-primary">

                    <tr>
                        <td>Nombre</td>
                        <td>Costo Presupuestado</td>
                        <td>Costo Real</td>
                        <td>Tienda</td>
                        <td>Estado</td>
                        <td>Notas</td>
                        <td>Acciones</td>            
                    </tr>

                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>${{ producto.costoPresupuestado }}</td>
                        <td>${{ producto.costoReal | default_if_none:"0" }}</td>
                        <td>{{ producto.tienda }}</td>
                        <td>{{ producto.estado }}</td>
                        <td>{{ producto.notas | default_if_none:"" }}</td>
                        <td>
                            {% comment %} <a class="btn btn-info producto" href="{% url 'listas:lista_add_producto' lista=1 producto=1 %}">Agregar</a> {% endcomment %}
                            <a class="btn btn-sm btn-danger" href="{% url 'listas:lista_remove_producto' %}?lista={{ lista.id | urlencode }}&producto={{ producto.id | urlencode }}" title="Quitar"><i class="fas fa-times"></i></a>
                            <a class="btn btn-sm btn-primary" href="{% url 'productos:producto_update' producto.id %}?next=listas&id={{lista.id}}" title="Editar"><i class="fas fa-edit"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>

    <!-- Productos disponibles -->
    <div class="col-md-3 p-0">
            {% if not listaProductos %}
            <p class="bg-warning p-3">No se han ingresado productos.</p>
            
            {% else %}
            <ul class="list-group">
                <li class="list-group-item active">Lista de productos disponbles</li>
                {% for producto in listaProductos %}
                    {% if not producto in productos %}
                        <li class="list-group-item d-flex">
                            {{ producto }}
                            <span class="ml-auto">
                                <a class="btn btn-sm btn-success" href="{% url 'listas:lista_add_producto' %}?lista={{ lista.id | urlencode }}&producto={{ producto.id | urlencode }}" title="Agregar"><i class="fas fa-plus"></i></a>
                                <a class="btn btn-sm btn-primary" href="{% url 'productos:producto_update' producto.id %}?next=listas&id={{lista.id}}" title="Editar"><i class="fas fa-edit"></i></a>
                            </span>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </div>    
</form>

</div>
{% endblock %}


{% block extrajs %}
<script>
var costoReal = "{{lista.costoTotalReal}}";
var costoPre = "{{lista.costoTotalPresupuestado}}";

var productos = (("{{productosJson}}").replace(/&(l|g|quo)t;/g, function(a,b){
    return {
        l   : '<',
        g   : '>',
        quo : '"'
    }[b];
}));
 
productos = JSON.parse( productos );

var oks = 0;
productos.forEach((producto) => {
    if (producto.fields.estado === 'Listo') {
        oks = oks + 1
    }    
});

if (productos.length != 0 && oks === productos.length) {
    Push.create("Alerta",{
        body:"Se ha completado la lista",
        timeout:5000,
        onClick:function(){
            this.close();
        }
    });
}

if (costoReal > costoPre) {
    Push.create("Alerta",{
        body:"Se ha excedido en el costo real",
        timeout:5000,
        onClick:function(){
            this.close();
        }
    });
}
</script>
{% endblock %}

apps/listas/templates/listas/lista_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Crear Lista {% endblock %}

{% block content %}
<div class="">
<h3 class="display-3">Listas</h3>
<hr>
</div>
<div class="col-md-12 p-0">
<form method="post" class="col-md-4 p-0">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.name}}">{{ field.label_tag }}</label><br>            
        {{ field }}
        <div class="bg-danger mt-1">{{ field.errors }}</div>
    </div>
    {% endfor %}

    <div class="bg-danger mt-1 mb-2">{{ form.non_field_errors }}</div>      

    <input type="submit" class="btn btn-success" value="Guardar" />
    <a class="ml-2" href="{% url 'listas:lista_list' %}">cancelar</a>
</form>
</div>
{% endblock %}

apps/listas/templates/listas/lista_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="col-md-12 p-0">
<h3 class="display-3">Listas</h3>
<hr>
<a class="btn btn-secondary" role="button" href="{% url 'listas:lista_form' %}">Agregar</a>
<hr>

{% if not listas %}

<p class="col-md-8 bg-danger p-2">No ha ingresado productos a la lista</p>

{% else %}
<div class="col-md-8 p-0 table-responsive">
<table class="table table-hover">
    <thead class="thead-light bg-primary">

        <tr>
            <td>Nombre</td>            
            <td>Costo total Presupuestado</td>
            <td>Costo total Real</td>
            <td>Estado</td>
            <td>Usuario</td>
            <td>Acciones</td>
        </tr>

    </thead>
    <tbody>
        {% for lista in listas %}
        <tr>
            <td>{{ lista.nombre }}</td>
            <td>${{ lista.costoTotalPresupuestado | default_if_none:"0" }}</td>
            {% if lista.costoTotalReal <= lista.costoTotalPresupuestado %}
            <td><span class="bg-bien">${{ lista.costoTotalReal | default_if_none:"0" }}</span></td>
            {% elif lista.costoTotalReal > lista.costoTotalPresupuestado %}            
            <td><span class="bg-pasado">${{ lista.costoTotalReal | default_if_none:"0" }}</span></td>
            {% else %}
            <td><span class="bg-bien">${{ lista.costoTotalReal | default_if_none:"0" }}</span></td>
            {% endif %}        
            <td>{{ lista.estado }}</td>
            <td>{{ lista.usuario }}</td>
            <td>        
                <a class="btn btn-sm btn-info lista mr-2" href="{% url 'listas:lista_detail' lista.id %}"><i class="fas fa-search"></i></a>
                <!-- <button class="btn btn-info lista" data-list="{{json}}" data-id="{{lista.id}}">Activar</button> -->
                <a class="btn btn-sm btn-primary mr-2" href="{% url 'listas:lista_update' lista.id %}" ><i class="fas fa-edit"></i></a>
                <a class="btn btn-sm btn-danger" href="{% url 'listas:lista_delete' lista.id %}"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endif %}

</div>
<br><br><br><br><br><br><br>
</div>

{% endblock %}