apps/tiendas/urls.py
from django.urls import path
from .views import TiendasList, TiendasCreate, TiendasUpdate, TiendasDelete, tiendas_list

app_name = 'tiendas'

urlpatterns = [
    path('', tiendas_list, name="tiendas_list"),
    path('crear/', TiendasCreate.as_view(), name="tiendas_form"),
    path('editar/<int:pk>', TiendasUpdate.as_view(), name="tiendas_update"),
    path('borrar/<int:pk>', TiendasDelete.as_view(), name="tiendas_delete"),
]

examen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    # path('', include('pwa.urls')),
    path('', include('social.apps.django_app.urls', namespace='social')), #social
    path('', include('apps.base.urls'), name="base"),
    path('admin/', admin.site.urls, name="admin"),
    path('tiendas/', include('apps.tiendas.urls'), name="tiendas"),
    path('productos/', include('apps.productos.urls'), name="productos"),
    path('login', include('apps.base.urls'), name="login"),
    path('logout', include('apps.base.urls'), name="logout"),
    path('listas/', include('apps.listas.urls'), name="listas"),
    
]

apps/tiendas/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

# Create your models here.

OPCIONES_ESTADO = (
    ('PENDIENTE', 'Pendiente'),
    ('APROBADA', 'Aprobada'),
)

class Tienda(models.Model):
    
    nombreTienda = models.CharField(max_length=50)
    nombreSucursal = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    estado = models.CharField(max_length=20, default="PENDIENTE", choices=OPCIONES_ESTADO)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreTienda + " - " + self.nombreSucursal

    class Meta:
        unique_together = ('nombreTienda', 'nombreSucursal', 'direccion', 'ciudad', 'region')


class TiendaForm(forms.ModelForm):

    class Meta:
        model = Tienda
        fields = [
            'nombreTienda',
            'nombreSucursal',
            'direccion',
            'ciudad',
            'region'
        ]
        labels = {
            'nombreTienda': "Nombre",
            'nombreSucursal': "Nombre de Sucursal",
            'direccion': "Dirección",
            'ciudad': "Ciudad",
            'region': "Región"
        }
        widgets = {
            'nombreTienda':forms.TextInput(attrs={'class':'form-control'}),
            'nombreSucursal':forms.TextInput(attrs={'class':'form-control'}),
            'direccion':forms.TextInput(attrs={'class':'form-control'}),
            'ciudad':forms.TextInput(attrs={'class':'form-control'}),
            'region':forms.TextInput(attrs={'class':'form-control'}),
        }
        error_messages = {
            '__all__': {
                'unique_together': 'La sucursal de esta tienda ya esta inscrita.',
            }
        }

apps/tiendas/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Tienda, TiendaForm

class OwnershipMixin(object):
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        current_user = self.request.user
        object_owner = getattr(self.get_object(), 'autor')

        if current_user != object_owner:
            return redirect('tiendas:tiendas_list')
        return super(OwnershipMixin, self).dispatch(request, *args, **kwargs)

@login_required(login_url='/')
def tiendas_list(request):
    tiendas_disp = Tienda.objects.filter(estado='APROBADA')
    tiendas_pers = Tienda.objects.filter(autor=request.user, estado='PENDIENTE')
    context = {'tiendas_disp':tiendas_disp, 'tiendas_pers':tiendas_pers}
    
    return render(request, 'tiendas/tiendas_list.html', context)

class TiendasList(ListView):                        
    model = Tienda
    template_name = 'tiendas/tiendas_list.html'
    queryset = Tienda.objects.all()
    paginate_by = 10

class TiendasCreate(CreateView):
    model = Tienda
    form_class = TiendaForm
    template_name = 'tiendas/tiendas_form.html'
    success_url = reverse_lazy('tiendas:tiendas_list')

    def get_success_url(self):
        next = self.request.GET.get('next', '')
        id = self.request.GET.get('id', '0')
        if next == 'productos':
            if id != '0':
                self.success_url = reverse_lazy('productos:producto_update', args=[id])
            else:
                self.success_url = reverse_lazy('productos:producto_form')   
        return self.success_url
    
    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super(TiendasCreate, self).form_valid(form)

class TiendasUpdate(OwnershipMixin, UpdateView):
    model = Tienda
    form_class = TiendaForm
    template_name = 'tiendas/tiendas_form.html'
    success_url = reverse_lazy('tiendas:tiendas_list')

    def get_success_url(self):
        next = self.request.GET.get('next', '')
        id = self.request.GET.get('id', '0')
        if next == 'productos':
            self.success_url = reverse_lazy('productos:producto_form', args=[id])   
        return self.success_url

class TiendasDelete(OwnershipMixin, DeleteView):
    model = Tienda
    template_name = 'tiendas/tiendas_borrar.html'
    success_url = reverse_lazy('tiendas:tiendas_list')

apps/tiendas/templates/tiendas/tiendas_borrar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="">

    <h3 class="display-3">Tiendas</h3>
    <hr>

    <form method="POST">{% csrf_token %}

        <div>       
            <h3>¿Desea eliminar el registro de la tienda {{object}}?</h3><br>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-success" href="{% url 'tiendas:tiendas_list' %}">Cancelar</a> 
            <br>
        </div>

    </form>
    <br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

apps/tiendas/templates/tiendas/tiendas_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Ingreso de Tienda{% endblock %}

{% block content %}
<div class="">
<h3 class="display-3">Tiendas</h3>
<hr>
</div>
<div class="col-lg-4 p-0">
<form method="post">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.name}}">{{ field.label_tag }}</label><br>            
        {{ field }}
        <div class="bg-danger mt-1">{{ field.errors }}</div>
    </div>
    {% endfor %}
    
    <div class="bg-danger mt-1 mb-2">{{ form.non_field_errors }}</div>

    <input type="submit" class="btn btn-success" value="Guardar" />
    <a class="ml-2" href="{% url 'tiendas:tiendas_list' %}">cancelar</a>
    <p class="text-muted">* Se debe esperar a que un administrador acepte la tienda, hasta entonces solo se podra usar la nueva tienda de manera personal.</p>
</form>
</div>
{% endblock %}

apps/tiendas/templates/tiendas/tiendas_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="">
<!-- <h1>Lista de Tiendas</h1> -->
<h3 class="display-3">Tiendas</h3>
<hr>
<a class="btn btn-secondary btn-sm" role="button" href="{% url 'tiendas:tiendas_form' %}">Agregar Tienda</a>
<hr>

<!-- Tiendas personales -->
<div class="row p-2">
<div class="col-lg-6 p-1">
<h2>Tiendas personales</h2>
<p class="text-info">Aquí apareceran las tiendas agregadas por ti, y que aun no hayan sido aprobadas por un administrador.</p>
{% if not tiendas_pers %}
<p class="bg-danger p-2">No hay tiendas personales</p>
{% else %}
<div class="table-responsive">
<table class="table table-hover">
    <thead class="bg-primary">
        <tr>
            <td>Tienda</td>
            <td>Sucursal</td>
            <td>Dirección</td>
            <td>Ciudad</td>
            <td>Región</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>  
        {% for tienda in tiendas_pers %}      
        <tr>
            {% comment %} <td><img src= ../../static/images/{{ perro.fotografia }} style="width: 100px;"/> </td> {% endcomment %}
            <td>{{ tienda.nombreTienda }}</td>
            <td>{{ tienda.nombreSucursal }}</td>
            <td>{{ tienda.direccion }}</td>
            <td>{{ tienda.ciudad }}</td>
            <td>{{ tienda.region }}</td>
            <td>
                <a class="btn btn-warning btn-sm mr-2" href="{% url 'tiendas:tiendas_update' tienda.id %}"><i class="fas fa-edit"></i></a>
                <a class="btn btn-danger btn-sm" href="{% url 'tiendas:tiendas_delete' tienda.id %}"><i class="fas fa-trash"></i></a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endif %}
</div>

<!-- <br><hr> -->

<!-- Tiendas disponibles -->
<div class="col-lg-6 p-1">
<h2>Tiendas disponibles</h2>
<p class="text-info">Aquí apareceran todas las tiendas de la comunidad, aprobadas por los administradores.</p>
<br class="d-none d-sm-block">
{% if not tiendas_disp %}
<p class="bg-danger p-2">No hay tiendas disponibles</p>
<br><br><br><br><br><br><br><br>
{% else %}
<div class="table-responsive">
<table class="table">
    <thead class="bg-primary">
        <tr>
            <td>Tienda</td>
            <td>Sucursal</td>
            <td>Dirección</td>
            <td>Ciudad</td>
            <td>Región</td>
        </tr>
    </thead>
    <tbody>  
        {% for tienda in tiendas_disp %}      
        <tr>
            {% comment %} <td><img src= ../../static/images/{{ perro.fotografia }} style="width: 100px;"/> </td> {% endcomment %}
            <td>{{ tienda.nombreTienda }}</td>
            <td>{{ tienda.nombreSucursal }}</td>
            <td>{{ tienda.direccion }}</td>
            <td>{{ tienda.ciudad }}</td>
            <td>{{ tienda.region }}</td>        
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
{% endif %}
</div>

</div>
{% endblock %}